import { moderator } from '../engines/moderator-engine.js';
import { bus, EVENTS } from '../core/bus.js';
import { DOM } from '../core/dom.js';
import { inputManager } from './input-manager.js';
import { inputRenderer } from './input-renderer.js';

const style = document.createElement('style');
style.textContent = `
#mod-trigger-btn,#mod-prefix-btn{position:fixed;bottom:15px;z-index:30;display:flex;align-items:center;justify-content:center;border:1px solid var(--white-a10);background:var(--bg-select);color:var(--white-a80);border-radius:8px;cursor:pointer;box-shadow:0 4px 16px rgba(0,0,0,.25)}
#mod-trigger-btn{right:12px;width:30px;height:30px}#mod-prefix-btn{right:50px;height:30px;padding:0 10px;font-size:12px}#mod-trigger-btn:hover,#mod-prefix-btn:hover{color:var(--color-accent);border-color:var(--color-accent)}
#mod-pop,#mod-panel{position:fixed;background:var(--bg-select);color:var(--white-a90);border:1px solid var(--white-a10);box-shadow:0 12px 36px rgba(0,0,0,.45);z-index:40}
#mod-pop{right:10px;bottom:52px;width:280px;padding:12px;border-radius:10px;display:none;gap:10px;flex-direction:column}#mod-pop.show{display:flex}
#mod-panel{inset:8vh 8vw;max-width:900px;margin:auto;border-radius:14px;display:none;flex-direction:column;overflow:hidden}#mod-panel.show{display:flex}
.mod-head,.mod-foot{padding:14px 18px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--white-a10)}.mod-foot{border-top:1px solid var(--white-a10);border-bottom:0;justify-content:flex-end;gap:8px}.mod-body{padding:18px;overflow:auto;display:flex;flex-direction:column;gap:16px}.mod-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:16px}.mod-card{border:1px solid var(--white-a10);border-radius:10px;padding:14px;display:flex;flex-direction:column;gap:10px}.mod-title{font-weight:700;font-size:15px}.mod-muted{color:var(--white-a50);font-size:12px}.mod-input,.mod-select,.mod-textarea{width:100%;box-sizing:border-box;background:var(--white-a03);color:inherit;border:1px solid var(--white-a10);border-radius:6px;padding:8px;font:inherit}.mod-textarea{resize:vertical}.mod-row{display:flex;gap:8px;align-items:center}.mod-row>*{min-width:0}.mod-rule{display:flex;gap:8px;align-items:center;padding:9px;border:1px solid var(--white-a10);border-radius:7px}.mod-rule span:first-child{flex:1;overflow-wrap:anywhere}.mod-btn{background:var(--color-accent);color:var(--color-bg);border:0;border-radius:6px;padding:8px 12px;cursor:pointer;font-size:12px}.mod-btn.secondary{background:var(--white-a10);color:inherit}.mod-close{background:transparent;border:0;color:inherit;font-size:20px;cursor:pointer}.mod-hits{font-size:12px;color:var(--status-error)}
@media(max-width:600px){#mod-panel{inset:0;border-radius:0}.mod-grid{grid-template-columns:1fr}.mod-body{padding:12px}#mod-prefix-btn{right:48px}}
`;
document.head.appendChild(style);

const trigger = document.createElement('button'); trigger.id = 'mod-trigger-btn'; trigger.setAttribute('aria-label', '打开禁词管理'); trigger.innerHTML = '⌁'; document.body.appendChild(trigger);
const prefix = document.createElement('button'); prefix.id = 'mod-prefix-btn'; prefix.textContent = '应用前缀'; prefix.setAttribute('aria-label', '应用最近命中的前缀'); document.body.appendChild(prefix);
const pop = document.createElement('div'); pop.id = 'mod-pop'; pop.innerHTML = '<div class="mod-title">禁词状态</div><div id="mod-status" class="mod-muted"></div><button class="mod-btn" id="mod-open">打开独立面板</button>'; document.body.appendChild(pop);
const panel = document.createElement('section'); panel.id = 'mod-panel'; panel.setAttribute('aria-label', '禁词管理面板'); panel.innerHTML = `
<div class="mod-head"><div><div class="mod-title">禁词管理</div><div class="mod-muted">仅扫描 AI 回复；测试文本不会进入真实流程</div></div><button class="mod-close" id="mod-close" aria-label="关闭">×</button></div>
<div class="mod-body"><div class="mod-grid"><div class="mod-card"><div class="mod-title">词库规则</div><div class="mod-row"><input class="mod-input" id="mod-word" placeholder="输入词条或通配模式"><select class="mod-select" id="mod-mode"><option value="contains">普通包含</option><option value="wildcard">通配符 * ?</option></select><button class="mod-btn" id="mod-add">添加</button><button class="mod-btn secondary" id="mod-add-temp">临时添加</button></div><div class="mod-muted">* 匹配任意长度，? 匹配单个字符；其他字符按原文匹配。</div><input class="mod-input" id="mod-search" placeholder="搜索词库"><div id="mod-list"></div></div><div class="mod-card"><div class="mod-title">前缀设置</div><textarea class="mod-textarea" id="mod-prefix" rows="5"></textarea><div class="mod-muted">使用 {words} 插入命中的词条。前缀只会写入输入框，不会自动发送。</div><button class="mod-btn" id="mod-save">保存设置</button><div class="mod-title">规则测试</div><textarea class="mod-textarea" id="mod-test" rows="4" placeholder="粘贴一段 AI 回复进行测试"></textarea><button class="mod-btn secondary" id="mod-run">测试识别</button><div id="mod-result" class="mod-hits"></div></div></div></div><div class="mod-foot"><button class="mod-btn secondary" id="mod-clear">清空临时词</button></div>`; document.body.appendChild(panel);
let lastHits = [];
function renderList() { const q = document.getElementById('mod-search').value.trim().toLowerCase(); const list = document.getElementById('mod-list'); list.innerHTML = ''; moderator.words.filter((w) => w.word.toLowerCase().includes(q)).forEach((w) => { const row = document.createElement('div'); row.className = 'mod-rule'; row.innerHTML = '<span>' + w.word + '</span><span class="mod-muted">' + (w.mode === 'wildcard' ? '通配' : '包含') + ' · ' + w.count + '</span><button class="mod-close" aria-label="删除 ' + w.word + '">×</button>'; row.querySelector('button').onclick = () => { moderator.removeWord(w.word, w.mode); renderList(); updateStatus(); }; list.appendChild(row); }); }
function updateStatus() { document.getElementById('mod-status').textContent = '已启用 ' + moderator.words.filter((w) => w.enabled).length + ' 条 · 最近命中 ' + lastHits.length + ' 条'; }
function applyHits(hits = lastHits) { if (!hits.length) return; const text = moderator.generatePrefix(hits) + '\n' + (inputManager.text || ''); DOM.hiddenInput.value = text; inputManager.text = text; inputManager.composing = false; inputManager.compData = ''; inputRenderer.markDirty(); DOM.hiddenInput.focus(); }
trigger.onclick = () => { pop.classList.toggle('show'); updateStatus(); };
prefix.onclick = () => applyHits();
document.getElementById('mod-open').onclick = () => { pop.classList.remove('show'); panel.classList.add('show'); document.getElementById('mod-prefix').value = moderator.prefixTemplate; renderList(); };
document.getElementById('mod-close').onclick = () => panel.classList.remove('show');
document.getElementById('mod-add').onclick = () => { const input = document.getElementById('mod-word'); if (!input.value.trim()) return; moderator.addWord(input.value, document.getElementById('mod-mode').value); input.value = ''; renderList(); updateStatus(); };
document.getElementById('mod-add-temp').onclick = () => { const input = document.getElementById('mod-word'); if (!input.value.trim()) return; moderator.addWord(input.value, document.getElementById('mod-mode').value, true); input.value = ''; renderList(); updateStatus(); };
document.getElementById('mod-search').oninput = renderList;
document.getElementById('mod-save').onclick = () => { moderator.prefixTemplate = document.getElementById('mod-prefix').value || moderator.prefixTemplate; moderator.save(); updateStatus(); };
document.getElementById('mod-run').onclick = () => { const hits = moderator.checkText(document.getElementById('mod-test').value); document.getElementById('mod-result').textContent = hits.length ? hits.map((h) => h.word + '：' + h.match.reason).join('；') : '未识别到命中'; };
document.getElementById('mod-clear').onclick = () => { moderator.words = moderator.words.filter((w) => !w.temporary); moderator.save(); renderList(); updateStatus(); };
bus.on(EVENTS.MODERATOR_HIT, (hits) => { lastHits = hits; updateStatus(); });
document.addEventListener('click', (event) => { if (!pop.contains(event.target) && event.target !== trigger && !trigger.contains(event.target)) pop.classList.remove('show'); });
