import { moderator } from '../engines/moderator-engine.js';
import { bus, EVENTS } from '../core/bus.js';
import { DOM } from '../core/dom.js';
import { inputManager } from './input-manager.js';
import { inputRenderer } from './input-renderer.js';

// 只挂载禁词自己的节点，关闭时不占用原聊天布局，也不触碰全屏编辑器。
document.querySelectorAll('#mod-trigger-btn, #mod-prefix-btn, #mod-pop, #mod-panel, #mod-backdrop, #mod-style').forEach((node) => node.remove());

const style = document.createElement('style');
style.id = 'mod-style';
style.textContent = `
/* 保留原 #fs-trigger-btn 的 right:20px / bottom:26px 位置；禁词快捷操作只排在它左侧，避免覆盖全屏编辑入口。 */
#mod-trigger-btn,#mod-prefix-btn{position:fixed;bottom:20px;z-index:10;height:32px;border:1px solid var(--white-a10);background:var(--bg-select);color:var(--white-a70);border-radius:8px;cursor:pointer;box-shadow:0 4px 16px rgba(0,0,0,.25);font:12px inherit}
#mod-trigger-btn{right:56px;width:32px;font-size:16px}#mod-prefix-btn{right:96px;padding:0 11px}#mod-trigger-btn:hover,#mod-prefix-btn:hover{color:var(--color-accent);border-color:var(--color-accent)}
#mod-pop,#mod-backdrop,#mod-panel{position:fixed;z-index:40}#mod-pop{right:12px;bottom:56px;width:276px;padding:13px;background:var(--bg-select);color:var(--white-a90);border:1px solid var(--white-a10);border-radius:10px;box-shadow:0 12px 36px rgba(0,0,0,.45);display:none;gap:10px;flex-direction:column}#mod-pop.show{display:flex}
#mod-backdrop{inset:0;background:rgba(0,0,0,.42);display:none}#mod-backdrop.show{display:block}
#mod-panel{inset:7vh 7vw;margin:auto;width:min(900px,86vw);height:min(720px,86vh);background:var(--bg-select);color:var(--white-a90);border:1px solid var(--white-a10);border-radius:14px;box-shadow:0 18px 60px rgba(0,0,0,.55);display:none;flex-direction:column;overflow:hidden}#mod-panel.show{display:flex}
.mod-head,.mod-foot{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 18px;border-bottom:1px solid var(--white-a10)}.mod-foot{justify-content:flex-end;border-top:1px solid var(--white-a10);border-bottom:0}.mod-body{min-height:0;padding:18px;overflow:auto}.mod-grid{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(260px,.8fr);gap:16px}.mod-card{min-width:0;border:1px solid var(--white-a10);border-radius:10px;padding:14px;display:flex;flex-direction:column;gap:10px}.mod-title{font-weight:700;font-size:15px}.mod-muted{color:var(--white-a50);font-size:12px;line-height:1.5}.mod-row{display:flex;align-items:center;gap:8px}.mod-row>*{min-width:0}.mod-input,.mod-select,.mod-textarea{box-sizing:border-box;width:100%;background:var(--white-a03);color:inherit;border:1px solid var(--white-a10);border-radius:6px;padding:8px;font:inherit}.mod-textarea{resize:vertical;line-height:1.5}.mod-btn{min-height:32px;background:var(--color-accent);color:var(--color-bg);border:0;border-radius:6px;padding:7px 11px;cursor:pointer;font-size:12px;white-space:nowrap}.mod-btn.secondary{background:var(--white-a10);color:inherit}.mod-btn:focus-visible,.mod-close:focus-visible,.mod-input:focus-visible,.mod-select:focus-visible,.mod-textarea:focus-visible{outline:2px solid var(--color-accent);outline-offset:2px}.mod-close{flex:0 0 auto;background:transparent;border:0;color:var(--white-a70);font-size:20px;cursor:pointer}.mod-rule{display:grid;grid-template-columns:minmax(0,1fr) auto auto;align-items:center;gap:8px;padding:9px;border:1px solid var(--white-a10);border-radius:7px}.mod-rule-word{min-width:0;overflow-wrap:anywhere}.mod-rule-actions{display:flex;align-items:center;gap:6px}.mod-check{accent-color:var(--color-accent)}.mod-hits{font-size:12px;color:var(--status-error);line-height:1.5}.mod-hit-list{display:flex;flex-wrap:wrap;gap:6px}.mod-chip{border:1px solid var(--color-accent-dim);background:var(--color-accent-soft);color:var(--color-accent-bright);border-radius:20px;padding:4px 8px;font-size:11px}
@media(max-width:680px){#mod-panel{inset:0;width:100%;height:100%;border-radius:0}.mod-head,.mod-foot{padding:12px 14px}.mod-body{padding:12px}.mod-grid{grid-template-columns:1fr}.mod-row{flex-wrap:wrap}.mod-row .mod-input{flex:1 1 100%}.mod-row .mod-select{flex:1 1 130px}.mod-row .mod-btn{flex:1}.mod-rule{grid-template-columns:minmax(0,1fr) auto}.mod-rule-actions{grid-column:1 / -1;justify-content:flex-end}}
@media(max-width:380px){#mod-prefix-btn{right:96px;padding:0 8px;font-size:11px}#mod-trigger-btn{right:56px}}
`;
document.head.appendChild(style);

const trigger = document.createElement('button');
trigger.id = 'mod-trigger-btn'; trigger.type = 'button'; trigger.setAttribute('aria-label', '打开禁词管理'); trigger.textContent = '⌁'; document.body.appendChild(trigger);
const prefix = document.createElement('button');
prefix.id = 'mod-prefix-btn'; prefix.type = 'button'; prefix.textContent = '应用前缀'; prefix.setAttribute('aria-label', '应用最近命中的前缀'); document.body.appendChild(prefix);
const pop = document.createElement('div');
pop.id = 'mod-pop'; pop.setAttribute('role', 'status'); pop.innerHTML = '<div class="mod-title">禁词状态</div><div id="mod-status" class="mod-muted"></div><div id="mod-hit-list" class="mod-hit-list"></div><button class="mod-btn" id="mod-open" type="button">打开管理面板</button>'; document.body.appendChild(pop);
const backdrop = document.createElement('div'); backdrop.id = 'mod-backdrop'; document.body.appendChild(backdrop);
const panel = document.createElement('section');
panel.id = 'mod-panel'; panel.setAttribute('role', 'dialog'); panel.setAttribute('aria-modal', 'true'); panel.setAttribute('aria-label', '禁词管理面板'); panel.innerHTML = `
<header class="mod-head"><div><div class="mod-title">禁词管理</div><div class="mod-muted">仅扫描 AI 回复，原聊天布局与全屏编辑器保持不变</div></div><button class="mod-close" id="mod-close" type="button" aria-label="关闭禁词管理">×</button></header>
<div class="mod-body"><div class="mod-grid"><div class="mod-card"><div class="mod-title">词库规则</div><div class="mod-row"><input class="mod-input" id="mod-word" aria-label="词条" placeholder="输入词条或通配模式"><select class="mod-select" id="mod-mode" aria-label="匹配方式"><option value="contains">包含匹配</option><option value="wildcard">通配符 * ?</option></select><button class="mod-btn" id="mod-add" type="button">添加</button><button class="mod-btn secondary" id="mod-add-temp" type="button">临时词</button></div><div class="mod-muted">* 匹配任意长度，? 匹配一个字符。临时词用于当前会话，可随时清除。</div><input class="mod-input" id="mod-search" aria-label="搜索词库" placeholder="搜索词库"><div id="mod-list"></div></div><div class="mod-card"><div class="mod-title">前缀设置</div><textarea class="mod-textarea" id="mod-prefix" rows="4" aria-label="前缀模板"></textarea><div class="mod-muted">用 {words} 插入命中的词条。应用只写入输入框，不会自动发送。</div><button class="mod-btn" id="mod-save" type="button">保存前缀</button><div class="mod-title">规则测试</div><textarea class="mod-textarea" id="mod-test" rows="4" aria-label="测试文本" placeholder="粘贴一段 AI 回复进行测试"></textarea><button class="mod-btn secondary" id="mod-run" type="button">测试识别</button><div id="mod-result" class="mod-hits" aria-live="polite"></div></div></div></div><footer class="mod-foot"><button class="mod-btn secondary" id="mod-clear" type="button">清空临时词</button></footer>`; document.body.appendChild(panel);

let lastHits = [];
const $ = (id) => document.getElementById(id);
function updateStatus() { $('mod-status').textContent = `已启用 ${moderator.words.filter((word) => word.enabled).length} 条 · 最近命中 ${lastHits.length} 条`; }
function renderList() { const query = $('mod-search').value.trim().toLocaleLowerCase(); const list = $('mod-list'); list.replaceChildren(); const words = moderator.words.filter((entry) => entry.word.toLocaleLowerCase().includes(query)); if (!words.length) { list.innerHTML = '<div class="mod-muted">暂无匹配词条</div>'; return; } words.forEach((entry) => { const row = document.createElement('div'); row.className = 'mod-rule'; const word = document.createElement('span'); word.className = 'mod-rule-word'; word.textContent = entry.word; const meta = document.createElement('span'); meta.className = 'mod-muted'; meta.textContent = `${entry.mode === 'wildcard' ? '通配' : '包含'} · ${entry.count}${entry.temporary ? ' · 临时' : ''}`; const actions = document.createElement('div'); actions.className = 'mod-rule-actions'; const check = document.createElement('input'); check.className = 'mod-check'; check.type = 'checkbox'; check.checked = entry.enabled; check.setAttribute('aria-label', `启用 ${entry.word}`); check.onchange = () => { entry.enabled = check.checked; moderator.save(); updateStatus(); }; const remove = document.createElement('button'); remove.className = 'mod-close'; remove.type = 'button'; remove.textContent = '×'; remove.setAttribute('aria-label', `删除 ${entry.word}`); remove.onclick = () => { moderator.removeWord(entry.word, entry.mode); renderList(); updateStatus(); }; actions.append(check, remove); row.append(word, meta, actions); list.appendChild(row); }); }
function applyHits(hits = lastHits) { if (!hits.length) return; const selected = [...document.querySelectorAll('#mod-hit-list .mod-chip[aria-pressed="true"]')].map((button) => button.dataset.word); const chosen = selected.length ? hits.filter((hit) => selected.includes(hit.word)) : hits; const text = `${moderator.generatePrefix(chosen)}\n${inputManager.text || ''}`; DOM.hiddenInput.value = text; inputManager.text = text; inputManager.composing = false; inputManager.compData = ''; inputRenderer.markDirty(); DOM.hiddenInput.focus(); }
function openPanel() { $('mod-prefix').value = moderator.prefixTemplate; renderList(); panel.classList.add('show'); backdrop.classList.add('show'); pop.classList.remove('show'); }
function closePanel() { panel.classList.remove('show'); backdrop.classList.remove('show'); }
trigger.onclick = () => { pop.classList.toggle('show'); updateStatus(); };
prefix.onclick = () => applyHits();
$('mod-open').onclick = openPanel; $('mod-close').onclick = closePanel; backdrop.onclick = closePanel;
$('mod-add').onclick = () => { const input = $('mod-word'); if (!input.value.trim()) return; moderator.addWord(input.value, $('mod-mode').value); input.value = ''; renderList(); updateStatus(); };
$('mod-add-temp').onclick = () => { const input = $('mod-word'); if (!input.value.trim()) return; moderator.addWord(input.value, $('mod-mode').value, true); input.value = ''; renderList(); updateStatus(); };
$('mod-search').oninput = renderList;
$('mod-save').onclick = () => { moderator.prefixTemplate = $('mod-prefix').value.trim() || moderator.prefixTemplate; moderator.save(); updateStatus(); };
$('mod-run').onclick = () => { const hits = moderator.checkText($('mod-test').value); $('mod-result').textContent = hits.length ? hits.map((hit) => `${hit.word}：${hit.match.reason}`).join('；') : '未识别到命中'; };
$('mod-clear').onclick = () => { moderator.words = moderator.words.filter((entry) => !entry.temporary); moderator.save(); renderList(); updateStatus(); };
bus.on(EVENTS.MODERATOR_HIT, (hits) => { lastHits = hits; $('mod-hit-list').replaceChildren(...hits.map((hit) => { const chip = document.createElement('button'); chip.type = 'button'; chip.className = 'mod-chip'; chip.textContent = hit.word; chip.dataset.word = hit.word; chip.setAttribute('aria-pressed', 'false'); chip.setAttribute('aria-label', `选择 ${hit.word}`); chip.onclick = () => { const active = chip.getAttribute('aria-pressed') === 'true'; chip.setAttribute('aria-pressed', String(!active)); }; return chip; })); updateStatus(); });
document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && panel.classList.contains('show')) closePanel(); });
document.addEventListener('click', (event) => { if (!pop.contains(event.target) && event.target !== trigger && !trigger.contains(event.target)) pop.classList.remove('show'); });

export { applyHits };
